# This is a basic workflow to help you get started with Actions

name: CI

  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: Run a one-line script
        uses: actions/github-script@v6
        with:
          retries: 3
          script: |
            let releases = await github.rest.repo.listReleases({owner: context.repo.owner, repo: context.repo.repo});
            console.log(JSON.stringify(releases.data));
            
            let release = await github.rest.repo.getReleaseByTag({
                owner: context.repo.owner,
                repo: context.repo.repo,
                tag: "idkever",
              });
